language: python
python:
  - "2.7"
env:
  - DJANGO=1.8
install:
  - pip install -r requirement/requirement.txt
before_script:
  - find ./ -name "*.sh" | xargs -l1 bash -n
  - find ./ -name "*.py" | xargs python -m py_compile
  - sh bin/init-secretkey.sh >> tttt/settings/basic.py
  - django-admin.py --version
  - python manage.py migrate --noinput
script:
  - python manage.py test apps.core.tests.SimpleTest
