---
- hosts: all
  remote_user: root
  ###gather_facts: no
  vars:
    homedir: "/data/greentea/web"
    greentea_user: "greentea"
    django_settings: "tttt.settings.production"
    elasticsearch: "elasticsearch.docker"
    elasticsearch_data_storage: "/usr/share/elasticsearch/data/"
  environment:
    DJANGO_SETTINGS_MODULE: "{{ django_settings }}"
  tasks:
    ## Elasticseach instance ###
    # only one instance of elastic search can be created
    - name: "Stop and backup old version of elasticsearch"
      shell: |
        COUNT=$( docker ps -aq -f "name={{elasticsearch}}" | wc -l )
        [ $COUNT -gt 0 ] && docker stop "{{elasticsearch}}" &&
            docker rename "{{elasticsearch}}" "{{elasticsearch}}.$COUNT"
      tags:
        - renew
        - renew-elasticserach
      register: out
    - debug: var=out.stdout_lines

    - name: "Create new Elasticsearch in Docker"
      shell: |
        docker pull elasticsearch:2
        docker run -d -p 9200:9200 -p 9300:9300 -v "{{elasticsearch_data_storage}}":"{{elasticsearch_data_storage}}" --name "{{elasticsearch}}" -h "{{elasticsearch}}" elasticsearch:2
      tags:
        - renew
        - renew-elasticserach
        - elasticserach

    - name: "Update project from Github"
      shell: |
        git fetch
        git reset --hard HEAD
        git pull
        source env/bin/activate
        python manage.py collectstatic --noinput
      become: yes
      become_user: "{{ greentea_user }}"
      args:
        chdir: "{{ homedir }}"
      tags:
        - update
        - deploy

    ## Grean tea instance ##
    - name: "Upgrade pip packages"
      shell: |
        source env/bin/activate
        pip freeze > /tmp/update.pip.now
        pip freeze | diff  /tmp/update.pip.now - >> pip-upgrade.log
        pip install --upgrade -r requirement/requirement.txt
      become: yes
      become_user: greentea
      args:
        chdir: "{{ homedir }}"
      tags:
        - upgrade

    - name: "Stop uwsgi instance of Django"
      shell:
        uwsgi --stop /run/greentea.pid
      tags:
        - deploy
        - upgrade
        - restart
        - stop

    - name: "Backup database"
      shell: |
        DB_NAME=$( python -c "from {{ django_settings }} import DATABASES; print DATABASES['default']['NAME']" )
        DB_HOST=$( python -c "from {{ django_settings }} import DATABASES; print DATABASES['default']['HOST']" )
        DB_USER=$( python -c "from {{ django_settings }} import DATABASES; print DATABASES['default']['USER']" )
        pg_dump "$DB_NAME" -U "$DB_USER" -h "$DB_HOST" | gzip > tttt.db.gz
      become: yes
      become_user: "{{ greentea_user }}"
      args:
        chdir: "{{ homedir }}"
      tags:
        - backup_db

    - name: "Fetch backup database"
      fetch: src=tttt.db.gz dest=tttt.db.gz flat=yes
      tags:
        - backup_db

    - name: "Migrate database schema"
      shell: |
        source env/bin/activate
        python manage.py migrate --noinput
      become: yes
      become_user: greentea
      args:
        chdir: "{{ homedir }}"
      tags:
        - deploy
        - migrate

    - name: "Start uwsgi instance of Django"
      shell:
        uwsgi -x /etc/uwsgi.d/tttt.conf
      tags:
        - deploy
        - upgrade
        - restart
        - start

    - name: "Check if pid exists and application runs"
      shell:
        ps aux | grep $(cat /run/greentea.pid) | grep -v grep

      tags:
        - deploy
        - upgrade
        - restart
        - start
...

